#!/bin/bash

source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_backup "$data_dir"

#=================================================
# BACKUP LOGROTATE
#=================================================

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/etc/sysctl.d/90-max_map_count-elasticsearch.conf"

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
