#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

if [ -e "/etc/sysctl.d/90-max_map_count-elasticsearch.conf" ]; then
	ynh_safe_rm "/etc/sysctl.d/90-max_map_count-elasticsearch.conf"
	# Reload the kernel configuration.
	if ! [ "${container:-}" = "lxc" ] # lxc doesn't allow sysctl to play with kernel options.
	then
		sysctl --system
	fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
